version: '2'
services:
  web:
    build: .
    env_file: config/.env
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/usr/src/app
      - bundler_cache:/usr/local/bundle
    command: bundle exec shotgun --port 3000 --host 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379"

volumes:
  bundler_cache:
    driver: local
